kind: pipeline
name: braid-sample


steps:
    - name: build
      image: golang:1.13.3
      commands:
        - export GOPROXY=https://goproxy.io
        - go version
        - go build -o base_linux base/main.go

    # 测试
    - name: test
      image: golang:1.13.3
      commands:
        - export GOPROXY=https://goproxy.io
        - export MOCK_REDIS_ADDR=redis://172.18.0.1:6379/0
        - export MOCK_CONSUL_ADDR=http://172.18.0.1:8900
        - export MOCK_JAEGER_ADDR=http://172.18.0.1:9411/api/v2/spans
        - export MOCK_NSQD_ADDR="172.18.0.1:4150"
        - export MOCK_NSQ_LOOKUPD_ADDR="172.18.0.1:4161"
        - ls

    # 推送
    - name: push
      image: plugins/docker
      settings:
        mirror: https://docker.mirrors.ustc.edu.cn
        username: pojol
        password: 
          from_secret: DOCKER_PASSWORD
        dockerfile: base/bin/Dockerfile
        repo: registry.cn-hangzhou.aliyuncs.com/braid-game/base
        registry: registry.cn-hangzhou.aliyuncs.com
        no_cache:
        tags:
          - latest
      when:
        branch:
          - develop

# 交付
    - name: deploy
      image: appleboy/drone-ssh
      settings:
        host: foo.com
        username: root
        key:
        from_secret: ssh_key
        port: 22
        script:
          - docker version
          - ls

# 清理
    - name: clean
      image: appleboy/drone-ssh