// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GuestRegistReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GuestRegistReq) Reset()         { *m = GuestRegistReq{} }
func (m *GuestRegistReq) String() string { return proto.CompactTextString(m) }
func (*GuestRegistReq) ProtoMessage()    {}
func (*GuestRegistReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}

func (m *GuestRegistReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GuestRegistReq.Unmarshal(m, b)
}
func (m *GuestRegistReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GuestRegistReq.Marshal(b, m, deterministic)
}
func (m *GuestRegistReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GuestRegistReq.Merge(m, src)
}
func (m *GuestRegistReq) XXX_Size() int {
	return xxx_messageInfo_GuestRegistReq.Size(m)
}
func (m *GuestRegistReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GuestRegistReq.DiscardUnknown(m)
}

var xxx_messageInfo_GuestRegistReq proto.InternalMessageInfo

type GuestRegistRes struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GuestRegistRes) Reset()         { *m = GuestRegistRes{} }
func (m *GuestRegistRes) String() string { return proto.CompactTextString(m) }
func (*GuestRegistRes) ProtoMessage()    {}
func (*GuestRegistRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{1}
}

func (m *GuestRegistRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GuestRegistRes.Unmarshal(m, b)
}
func (m *GuestRegistRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GuestRegistRes.Marshal(b, m, deterministic)
}
func (m *GuestRegistRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GuestRegistRes.Merge(m, src)
}
func (m *GuestRegistRes) XXX_Size() int {
	return xxx_messageInfo_GuestRegistRes.Size(m)
}
func (m *GuestRegistRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GuestRegistRes.DiscardUnknown(m)
}

var xxx_messageInfo_GuestRegistRes proto.InternalMessageInfo

func (m *GuestRegistRes) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*GuestRegistReq)(nil), "api.guestRegistReq")
	proto.RegisterType((*GuestRegistRes)(nil), "api.guestRegistRes")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_67c21677aa7f4e4f) }

var fileDescriptor_67c21677aa7f4e4f = []byte{
	// 117 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xc9, 0x4f, 0xcf,
	0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0x12, 0xe0, 0xe2,
	0x4b, 0x2f, 0x4d, 0x2d, 0x2e, 0x09, 0x4a, 0x4d, 0xcf, 0x04, 0x91, 0x85, 0x4a, 0x6a, 0x68, 0x22,
	0xc5, 0x42, 0x22, 0x5c, 0xac, 0x21, 0xf9, 0xd9, 0xa9, 0x79, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c,
	0x41, 0x10, 0x8e, 0x91, 0x33, 0x17, 0x2b, 0xd8, 0x34, 0x21, 0x2b, 0x2e, 0x1e, 0xb0, 0x86, 0xf8,
	0x22, 0xb0, 0x0e, 0x21, 0x61, 0xbd, 0xc4, 0x82, 0x4c, 0x3d, 0x54, 0x53, 0xa5, 0xb0, 0x08, 0x16,
	0x2b, 0x31, 0x24, 0xb1, 0x81, 0x9d, 0x62, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x23, 0xcf, 0xbe,
	0xed, 0x99, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LoginClient is the client API for Login service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoginClient interface {
	GuestRegist(ctx context.Context, in *GuestRegistReq, opts ...grpc.CallOption) (*GuestRegistRes, error)
}

type loginClient struct {
	cc *grpc.ClientConn
}

func NewLoginClient(cc *grpc.ClientConn) LoginClient {
	return &loginClient{cc}
}

func (c *loginClient) GuestRegist(ctx context.Context, in *GuestRegistReq, opts ...grpc.CallOption) (*GuestRegistRes, error) {
	out := new(GuestRegistRes)
	err := c.cc.Invoke(ctx, "/api.login/guest_regist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginServer is the server API for Login service.
type LoginServer interface {
	GuestRegist(context.Context, *GuestRegistReq) (*GuestRegistRes, error)
}

// UnimplementedLoginServer can be embedded to have forward compatible implementations.
type UnimplementedLoginServer struct {
}

func (*UnimplementedLoginServer) GuestRegist(ctx context.Context, req *GuestRegistReq) (*GuestRegistRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GuestRegist not implemented")
}

func RegisterLoginServer(s *grpc.Server, srv LoginServer) {
	s.RegisterService(&_Login_serviceDesc, srv)
}

func _Login_GuestRegist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuestRegistReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServer).GuestRegist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.login/GuestRegist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServer).GuestRegist(ctx, req.(*GuestRegistReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Login_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.login",
	HandlerType: (*LoginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "guest_regist",
			Handler:    _Login_GuestRegist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "login.proto",
}
